### ISSUE TITLE
Presentation Needs

### ISSUE THREAD

**Issue by UberKitten** [UberKitten/barcOwned#16]
This will be a running list of things that need to be/should be done before the presentation that don't involve code:

- ~~Acquire more scanners~~ Partially done
- "kick me" QR code stickers professionally made
- #cyberbarcode stickers professionally made
- Any other sticker ideas?
- ~~Extra #cyberbarcode shirt for @magicspacekiwi - or I can give you mine, as it's an XL and doesn't fit me anymore~~

**Comment by T3hUb3rK1tten** [comment]
Was recommended moo.com and uprinting.com for stickers
